# Site settings
title: Low Key Pro
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/low-key-pro" # the subpath of your site, e.g. /blog/
url: "http://coltonfitzgerald.github.io/low-key-pro" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /event/:year/:month/:day/:title/
